name: Build MoveWindowsHere Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-windows-x86_64:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore MoveWindowsHere.sln

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build MoveWindowsHere
      run: |
        msbuild.exe MoveWindowsHere.sln /p:platform="Any CPU" /p:configuration="Release"

    - name: Upload Windows x86_64 build
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: windows-x86_64-build
        path: MoveWindowsHere/bin/Release/MoveWindowsHere.exe